apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  namespace: backend-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
        - name: sensor-simulator
          image: whu1/sensor-simulator:2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service.backend-workshop.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_VHOST
              value: "/"
            - name: EXCHANGE_NAME
              value: sim_sensor_exchange
            - name: ROUTING_KEY
              value: sensor.data
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
