apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-html-<naam>
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Backend Workshop</title>
      <style>
        body {
          background: #eef2f7;
          font-family: Arial;
          text-align: center;
          padding: 80px;
        }
        h1 { color: #2563eb; }
      </style>
    </head>
    <body>
      <h1>Backend Workshop</h1>
      <h2>Mijn eerste Kubernetes Deployment!</h2>
      <p>Deze pagina draait in een NGINX-container.</p>
      <p>De HTML komt uit een Kubernetes ConfigMap.</p>
    </body>
    </html>
